### ISSUE TITLE
WARN  merino > Init: Unsupported version: SOCKS67

### ISSUE THREAD

**Issue by travismoran** [ajmwagar/merino#13]
I am able to build and run Merino but when I attempt to connect with or without authentication, using dns or the IP of the host I get the following error.
`WARN  merino > Init: Unsupported version: SOCKS67`

**Comment by Gordon01** [comment]
What client do you use to connect?

**Comment by travismoran** [comment]
Firefox is the one that I was having trouble with, this fork seems to be working for chrome though.
https://github.com/zaqxsw-dev/merino
[https://opengraph.githubassets.com/748b50e3837dcfa964be42bfc173ac4c4ff8f6ae09b8a6c28aabde0617d2fdbb/zaqxsw-dev/merino]<https://github.com/zaqxsw-dev/merino>
GitHub - zaqxsw-dev/merino: A SOCKS5 Proxy server written in Rust<https://github.com/zaqxsw-dev/merino>
:sheep: A SOCKS5 Proxy server written in Rust. Contribute to zaqxsw-dev/merino development by creating an account on GitHub.
github.com

________________________________

**Comment by Gordon01** [comment]
Did you compile merino from source?
```
git clone https://github.com/ajmwagar/merino
cd merino
cargo install --path .
```

**Comment by Jarsop** [comment]
It seems not a bug related to `merino`. Apparently your firefox does not seem to send a SOCKS request (there is no RFC SOCKS67 :yum: )

For your information I had this problem while trying the proxy on Spotify (on Linux)
A `netcat` listening to the port instead of the proxy returned me:

```bash
❯ nc -l localhost 4000
CONNECT login5.spotify.com:443 HTTP/1.1
Host: login5.spotify.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Spotify/1.1.84.716 Safari/537.36

OK
```
Note that the first character is 'C' and `'C' == 67 (decimal)` in ASCII hence the `SOCKS67` (unknown code formatted [here](https://github.com/ajmwagar/merino/blob/aa083b33b75d401b9f5bdaa5b1b6171073895f68/src/lib.rs#L339))

For me the problem was the GUI not configuring the sock5/4 proxy properly and sent a HTTP request.
So I had to configure correctly the proxy address in the configuration files directly.

Hope this helpful

**Comment by travismoran** [comment]
Nice! thanks all for the support :)

**Comment by Jarsop** [comment]
> Nice! thanks all for the support :)

You're welcome, @travismoran does it make sense to have an error handling about HTTP requests received ?
